spring:
  application:
    name: mongodb
  mongodb:
    uri: ${DATABASE_URL}

server:
  port: ${SERVER_PORT:8085}

rapidapi:
  key: ${RAPIDAPI_KEY}
  host: ${RAPIDAPI_HOST}
  spotify:
    key: ${RAPIDAPI_SPOTIFY_KEY}
    host: ${RAPIDAPI_SPOTIFY_HOST}
