# kubectl apply -f karla-magallanes-25-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: karla-magallanes-25-secret
  namespace: karla-magallanes-25-namespace
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9hbnllbGk6QWRtaW4yODI4QGNsdXN0ZXIwLjB3c3BoY3gubW9uZ29kYi5uZXQvWW91VHViZV9NUDM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5   # en Base64
  RAPIDAPI_KEY: MWYyNjIzYTQ5MW1zaDQ4NmVmZjMwNmY1ZDE0M3AxNWFkYjBqc25mNTVmODQwOWJlN2E=   # en Base64
  RAPIDAPI_HOST: eW91dHViZS1tcDM2LnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_SPOTIFY_KEY: MWYyNjIzYTQ5MW1zaDQ4NmVmZjMwNmY1ZDE0M3AxNWFkYjBqc25mNTVmODQwOWJlN2E=   # en Base64
  RAPIDAPI_SPOTIFY_HOST: c3BvdGlmeS1tdXNpYy1tcDMtZG93bmxvYWRlci1hcGkucC5yYXBpZGFwaS5jb20=   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode